services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: sachi-laracrud
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:   
            - app_network
    db:
        image: mysql:8.0.40
        container_name: db
        restart: unless-stopped
        ports:
            - "3315:3306"
        environment:
            MYSQL_DATABASE: crud
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: web_server
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
